#!/usr/bin/env python

import os
import sys
import argparse
from redmine import Redmine
from IPython import embed

#def create_project_dict():
    #return { project.name: project.id for project in redmine.project.all() }

def subcommand_shell(args):
    embed()

def subcommand_update_versions(args):
    embed()

def subcommand_add_related_tickets(args):
    target_issue = redmine.issue.get(args.target)
    if args.ids:
        ids = args.ids
    else:
        embed()

    for id in ids:
        try:
            redmine.issue_relation.create(issue_id=args.target, issue_to_id=id)
        except (redmine.exceptions.ValidationError, redmine.exceptions.ResourceError) as e:
            print("x")

def build_parser():
    parser = argparse.ArgumentParser(prog="redshell")
    subparsers = parser.add_subparsers(help="sub-command help")
    
    parser_shell = subparsers.add_parser("shell")
    parser_shell.set_defaults(func=subcommand_shell)
    
    parser_uv = subparsers.add_parser("update_versions")
    parser_uv.add_argument("--query_id", type=str, help="filter query id")
    parser_uv.add_argument("--version", type=str, help="version for updating")
    parser_uv.set_defaults(func=subcommand_update_versions)
    
    parser_art = subparsers.add_parser("add_related_tickets")
    parser_art.add_argument("--target", type=str, required=True, help="target ticket id")
    parser_art.add_argument("--query_id", type=str, help="filter query id")
    parser_art.add_argument("--ids", nargs="+", type=int, help="ticket ids")
    parser_art.set_defaults(func=subcommand_add_related_tickets)

    return parser

if not "REDMINE_URL" in os.environ:
    sys.exit("Please specify envinronment variable: 'REDMINE_URL'")
if not "REDMINE_API_TOKEN" in os.environ:
    sys.exit("Please specify envinronment variable: 'REDMINE_API_TOKEN'")

redmine = Redmine(os.environ["REDMINE_URL"], key=os.environ["REDMINE_API_TOKEN"])

parser = build_parser()
args = parser.parse_args()
args.func(args)
